### ISSUE TITLE
Vector type cast throws Unhandled Exception

### ISSUE THREAD

**Issue by TiLogic** [Tensegritics/ClojureDart#101]
ClojureDart version: `81a624a27dad8c9b92856dbb86791013bf11498f`

Type casting a vector fails with the following error:

`Unhandled Exception: type 'PersistentVector<dynamic>' is not a subtype of type 'Iterable<String>' in type cast`

Example:
```clojure
(defn without-cast
  [path]
  (Uri.
   :path (when (string? path) path)
   :pathSegments (when (coll? path) path)))

(without-cast "first")
;=> OK

(without-cast ["first" "second"])
;=> Unhandled Exception: type 'PersistentVector<dynamic>' is not a subtype of type 'Iterable<String>' in type cast

(defn with-cast
  [path]
  (Uri.
   :path (when (string? path) path)
   :pathSegments (when (coll? path) ^#/(Iterable String) path)))

(with-cast ["first" "second"])
;=> Unhandled Exception: type 'PersistentVector<dynamic>' is not a subtype of type 'Iterable<String>' in type cast
```

**Comment by cgrand** [comment]
It's an instance of #14.

**Comment by cgrand** [comment]
@TiLogic `without-cast` works now. `with-cast` doesn't and it's by design.
 Let me explain the rationale: when you type hint an expression it's to give to the compiler a hint to the actual type of the value: the compiler will trust this hint and won't try to make any clever cast. Thus a vector of objects will ne ever be list of strings.
However when doing interop and calling a method which expects an `Iterable<String>` then the compiler emits more clever code to attempt to produce a value of this type from the actual value.

**Comment by TiLogic** [comment]
Thanks for the fix and the explanation!
